# Generated by Django 2.0.2 on 2019-01-29 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('level', models.CharField(default='beginner', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain_description', models.CharField(max_length=200)),
                ('complain_address', models.CharField(max_length=100)),
                ('complain_category', models.CharField(max_length=20)),
                ('complain_type', models.CharField(default='complain', max_length=20)),
                ('complain_status', models.CharField(default='pending', max_length=20)),
                ('complain_priority', models.IntegerField(default=1)),
                ('complain_rating', models.IntegerField(default=0)),
                ('post_to_wall', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(blank=True, default=datetime.date(2019, 1, 29))),
                ('complain_count', models.IntegerField(default=1)),
                ('complain_uname', models.CharField(max_length=30, null=True)),
                ('complain_image', models.ImageField(null=True, upload_to='./demo/static/demo/images/')),
            ],
        ),
    ]
