# Generated by Django 2.0.2 on 2019-01-29 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.date(2019, 1, 29)),
        ),
        migrations.AlterField(
            model_name='complain',
            name='post_to_wall',
            field=models.BooleanField(default=False),
        ),
    ]
