# Generated by Django 2.0.2 on 2019-01-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='complain_image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='complain',
            name='complain_uname',
            field=models.CharField(default='ravi', max_length=30, null=True),
        ),
    ]
