# Generated by Django 2.0.2 on 2019-01-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20190129_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='date_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
