# Generated by Django 2.0.2 on 2019-01-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20190129_2255'),
        ('demo', '0003_auto_20190129_2310'),
    ]

    operations = [
    ]
