# Generated by Django 2.0.2 on 2019-02-05 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_merge_20190201_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_complain_id', models.IntegerField(default=1)),
                ('feed_username', models.CharField(default='ravi', max_length=30, null=True)),
                ('feed_feedback', models.CharField(max_length=200)),
                ('feed_date_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 6, 0, 47, 17, 26530))),
            ],
        ),
        migrations.AlterField(
            model_name='complain',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.date(2019, 2, 6)),
        ),
    ]
