# Generated by Django 2.0.2 on 2019-01-29 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20190129_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.date(2019, 1, 30)),
        ),
    ]
