# Generated by Django 2.0.2 on 2019-03-02 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20190130_0016'),
        ('demo', '0005_auto_20190206_0047'),
    ]

    operations = [
    ]
