# Generated by Django 2.0.2 on 2019-02-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20190130_0016'),
        ('demo', '0004_merge_20190201_1950'),
    ]

    operations = [
    ]
