# Generated by Django 2.0.2 on 2019-02-05 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_merge_20190205_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.date(2019, 2, 5)),
        ),
    ]
