# Generated by Django 2.0.2 on 2019-03-02 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_merge_20190302_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='complain_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='complain',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.date(2019, 3, 2)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feed_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 9, 30, 33, 107013)),
        ),
    ]
