# Generated by Django 2.0.2 on 2019-03-17 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_auto_20190302_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.IntegerField(default=1)),
                ('user_id', models.IntegerField(default=1)),
                ('complain_id', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=30)),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='complain',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.date(2019, 3, 17)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feed_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 17, 15, 12, 36, 890840)),
        ),
    ]
