# Generated by Django 2.0.2 on 2019-03-17 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_auto_20190317_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='user_name',
            field=models.CharField(default='ravi', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feed_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 17, 15, 27, 10, 66298)),
        ),
    ]
