# Generated by Django 2.0.2 on 2019-03-17 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_auto_20190317_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_id', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='complain',
            name='complain_rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feed_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 17, 16, 55, 45, 621403)),
        ),
    ]
