# Generated by Django 2.0.2 on 2019-03-17 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_auto_20190317_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feed_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 17, 17, 0, 4, 218505)),
        ),
    ]
