# Generated by Django 2.0.2 on 2019-03-17 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_auto_20190317_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feed_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 17, 17, 2, 38, 990500)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
