# Generated by Django 2.1.7 on 2019-03-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0015_auto_20190317_1708'),
        ('demo', '0008_auto_20190205_2328'),
    ]

    operations = [
    ]
