# Generated by Django 2.0.2 on 2019-03-19 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0016_auto_20190319_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain_id', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feed_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 19, 23, 20, 17, 712782)),
        ),
    ]
