# Generated by Django 2.0.2 on 2019-03-19 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0018_auto_20190319_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='level',
            field=models.CharField(default='soldier', max_length=50),
        ),
        migrations.AlterField(
            model_name='complain',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.date(2019, 3, 20)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feed_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 20, 0, 58, 39, 573819)),
        ),
    ]
