# Generated by Django 2.0.2 on 2019-03-24 08:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo', '0021_auto_20190321_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='image',
            field=models.CharField(default='/static/profiles/NoImage.png', max_length=200),
        ),
        migrations.AddField(
            model_name='citizen',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complain',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.date(2019, 3, 24)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feed_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 24, 14, 26, 49, 293337)),
        ),
    ]
